name: master
on:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: pip install .
    - run: pip install pre-commit pytest python-semantic-release
    - run: git config --global user.name "github-actions"
    - run: git config --global user.email "action@github.com"
